# Generated by Django 3.2.7 on 2021-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=40)),
                ('solicitante', models.CharField(max_length=100)),
                ('documento_solicitante', models.CharField(max_length=15)),
                ('representante', models.CharField(max_length=100)),
                ('documento_representante', models.CharField(max_length=15)),
                ('correo_representante', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
