# Generated by Django 3.0.7 on 2021-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210929_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_diagnostico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
